### ISSUE TITLE
No `retention-days` for `prepare-index` step

### ISSUE THREAD

**Issue by aKuad** [aKuad/web-intercom#259]
## Description

In `cd-pages.yml:18`

```yml
    - name: Output page as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: index
        path: src/index.html
```

This step has no parameter of `retention-days`. Unify to other build steps: `retention-days: 1`.
