### ISSUE TITLE
At Deno test failed, converage report is not generated

### ISSUE THREAD

**Issue by aKuad** [aKuad/web-intercom#280]
## Description

At `cd-pages.yml`:

```yml
    - name:
      run: deno test --parallel --coverage
    - name: Export coverage report as HTML
      run: deno coverage --html
```

If Deno test been failed, coverage report will be skipped.

Modify it to `deno coverage --html` run always.
